### ISSUE TITLE
本地路径如何安装依赖

### ISSUE THREAD

**Issue by da-cai-ji** [shanziSZ/MMQL#1]
absl-py @ file:///croot/absl-py_1686852429912/work
您好，请教一下类似于[requirements.txt]中的以上命令，该如何安装对应的依赖呢

**Comment by shanziSZ** [comment]
无需担心这些，系统生成的requirement远超运行需要的环境，直接安装代码文件里import的包就可以

**Comment by da-cai-ji** [comment]
感谢回复，可以成功运行了，但是在测试时我遇到一个小问题，就是训练和测试的total不一致呢，如（slake数据集）：
训练过程：[Result] Loss:0.000000, The acc is 86.324783%, The correct num is 909.0, the acc of open question is 85.261497%, the acc of close question is 87.914696%
测试过程：[Result] Loss:0.000000, The acc is 85.673889%, The correct num is 909.0, the acc of open question is 82.945732%, the acc of close question is 89.903847%
correct num都是909，但是acc却不一致
我将total打印出来发现训练时的total为1053，测试时total为1061，这相差的几个具体是什么作用呢？

**Comment by shanziSZ** [comment]
SLAKE数据集分为train， validate，和test。我们的实验按照标准的流程在validate（1053条英语样本）上进行模型结构和超参数调节，并在test（1061条样本）上进行测试。1053是validate数据集的样本数。
