### ISSUE TITLE
image_mask

### ISSUE THREAD

**Issue by Peak925** [shanziSZ/MMQL#2]
请问image_mask是在哪里生成的呢？我好像没找到，麻烦大佬解答一下~

**Comment by shanziSZ** [comment]
我代码里也没有用到image_mask啊

**Comment by Peak925** [comment]
哦哦好像是没有，但是这样的话，在融合模块里面怎么知道image不同位置的权重得分呢？还是说只有交叉注意力时候才用到这个？我看大佬你的代码里融合模块用的nn.Transformer，是没有用到交叉注意力吗？

**Comment by shanziSZ** [comment]
我们没有使用交叉注意力，image和融合部分的改进不是本工作的主要内容，因此我们仅使用最简单的融合方法

**Comment by Peak925** [comment]
> 我们没有使用交叉注意力，image和融合部分的改进不是本工作的主要内容，因此我们仅使用最简单的融合方法

好滴好滴！我还有一个问题，希望大佬解答一下~。就是dataset_SLAKE_group.py 的190行random.random()<0.7，为什么要做这个判断呢？以及open_close_clean这个参数记录的是什么呀，为什么只有满足随机值小于0.7才记录？我这个地方没有太理解，感谢大佬回复~~~

**Comment by shanziSZ** [comment]
对于VQA-RAD数据集，一张图片有几个问题在训练集中，剩下几个问题在测试集中。因此对于一张图片，在推理的过程中，添加那些在训练集中的问题及其对于答案，可以提高问答的准确率。基于这个试验结果提出一个假设：那些已经回答完成的问题及其答案可以用作后续还没有被回答问题的提示词。

但是VQA-RAD的问题在于其切分方式，一张图片的相关问题横跨了训练集和测试集，同时测试集中的图片被几乎完整的包括在了训练集中。这在实际应用中是不现实的。

而SLAKE数据集，在图片层面，训练集和测试集是不相交的，更符合实际情况。因此为了测试我们的假设，我们人为构造了一个SLAKE的变体，每一张图片有一部分问题，被认为已经回答了，用于构建成为提示词。在测试集中，我们通过provided.txt文件直接指定了那些问题被回答。在训练集合中，我们没有进行指定，使用随机函数进行抽样。

一个batch 16张图片，每个图片拥有的问题数量不同。因此，为了满足dataloader的要求，即张量大小一致，我们设定了每个图像的最大问题数量为20，对于问题数小于20的图片填充空问题。在最后模型运时，16*20个问题被flatten到320，再去除空问题以后变为200个问题（假设）。这200个问题根据是open_end 还是 close_end，通过separate函数送往对应的classifier。因此假设有200个问题，open_close_clean的长度就为200，其中记录了每个问题是open_end 还是 close_end。P.S.对于每个图像，这20个问题中前多少个是真正的问题，我们通过q_num记录下来。

**Comment by Peak925** [comment]
> 对于VQA-RAD数据集，一张图片有几个问题在训练集中，剩下几个问题在测试集中。因此对于一张图片，在推理的过程中，添加那些在训练集中的问题及其对于答案，可以提高问答的准确率。基于这个试验结果提出一个假设：那些已经回答完成的问题及其答案可以用作后续还没有被回答问题的提示词。
> 
> 但是VQA-RAD的问题在于其切分方式，一张图片的相关问题横跨了训练集和测试集，同时测试集中的图片被几乎完整的包括在了训练集中。这在实际应用中是不现实的。
> 
> 而SLAKE数据集，在图片层面，训练集和测试集是不相交的，更符合实际情况。因此为了测试我们的假设，我们人为构造了一个SLAKE的变体，每一张图片有一部分问题，被认为已经回答了，用于构建成为提示词。在测试集中，我们通过provided.txt文件直接指定了那些问题被回答。在训练集合中，我们没有进行指定，使用随机函数进行抽样。
> 
> 一个batch 16张图片，每个图片拥有的问题数量不同。因此，为了满足dataloader的要求，即张量大小一致，我们设定了每个图像的最大问题数量为20，对于问题数小于20的图片填充空问题。在最后模型运时，16*20个问题被flatten到320，再去除空问题以后变为200个问题（假设）。这200个问题根据是open_end 还是 close_end，通过separate函数送往对应的classifier。因此假设有200个问题，open_close_clean的长度就为200，其中记录了每个问题是open_end 还是 close_end。P.S.对于每个图像，这20个问题中前多少个是真正的问题，我们通过q_num记录下来。

好的大佬，我大概了解了，感谢回复！

**Comment by Peak925** [comment]
大佬您好，我最近又回顾了一下论文，又有几个问题想要请教一下~。论文里说的“医学诊断是基于多种因素的，因此与同一图像相关的问题应该一起回答。”是为什么呢？以及，你提出的单个图像相关的多个医学问题一同训练，在代码里是不是体现在当假定每个图像的最大问题数量为20时，训练这一个图像的20个问题？而不是像常规的VQA方法，针对20个不同的图片的20个问题训练？

**Comment by Peak925** [comment]
还有就是dataset_SLAKE_group.py 的190行random.random()<0.7这句代码，是为了屏蔽答案成为MASK，有什么用处呢？
