### ISSUE TITLE
if self.groupedEntries[image_id]['q_token']["input_ids"][mask_idx] == 103:

### ISSUE THREAD

**Issue by Peak925** [shanziSZ/MMQL#3]
求作者解答，datasset_RAD_group.py文件中这句代码我没看懂，这里的103指的是什么呀？谢谢~

**Comment by shanziSZ** [comment]
Bert tokenizer 中 '[MASK]' 这个特殊token的下标

**Comment by Peak925** [comment]
感谢~我已经理解了

> Bert tokenizer 中 '[MASK]' 这个特殊token的下标
